version: '2'

services:
  theia-ide:
    network_mode: "host"
    ports:
      - ${RHPORT}:${RHPORT}
    build: ./
    user: ${CURRENT_UID}
    command:
      sh -c 'cd /home/theia && yarn theia start /my-workspace --hostname 0.0.0.0 --port ${RHPORT}'
    volumes:
      - ../:/my-workspace
